name: kalpaniksaathi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_button: ^0.2.0
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  file_picker: ^4.3.0
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.5.3
  flutter_vector_icons: ^1.0.0
  font_awesome_flutter: null
  http: ^0.13.4
  image_picker: ^0.8.4+4
  json_serializable: ^6.1.4
  like_button: ^2.0.4
  mime: ^1.0.1
  open_file: ^3.2.1
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^6.0.2
  test: ^1.17.10
  uuid: ^3.0.5
  velocity_x: ^3.4.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/messages.json
    - assets/audio.json

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: WorkSansLight
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Light.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

    - family: Schoolbell
      fonts:
        - asset: assets/fonts/Schoolbell/Schoolbell-Regular.ttf
